services:
  app:
    build: .
    container_name: maps-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./my-app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development